version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:5000"
    env_file:
      - .env
    depends_on:
      - postgres_database
    restart: unless-stopped
  postgres_database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
